jobtype: STR
jobname: 아델
vEnhanceNum: 10
preEmptiveSkills: 1
passive_skill_list:
- name: 매직 서킷
  att: weapon_att * 0.15
- name: 패이스
  crit_damage: 10
  patt: 10
- name: 루디먼트
  att: 30
- name: 마스터리
  att: 30
- name: 트레인
  stat_main: 60
- name: 어센트
  att: 30
  pdamage_indep: 15
  crit: 20
- name: 엑스퍼트
  att: 30
- name: 데몰리션
  pdamage_indep: 30 + passive_level
  armor_ignore: 20 + passive_level
- name: 어테인
  att: 30 + passive_level
  boss_pdamage: 10 + math.ceil(passive_level / 2)
  crit: 20 + passive_level
not_implied_skill_list:
- name: 무기상수
  pdamage_indep: 34
- name: 숙련도
  mastery: 90 + math.ceil(passive_level / 2)
constant:
  DOT_PUNISHER_HIT: 22
  ERUPTION_RATE:
  - 0
  - 0
  - 20
  - 45
  - 80
  - 125
skills:
  샤드:
    cooltime: 6000
    delay: 630
    red: true
    damage: 80 + 30 + 115 + 225 + passive_level * 3
    hit: 15
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 6
    v_increment: 2
    v_crit: true
  샤드(원더):
    cooltime: 8000
    delay: 0
    damage: 80 + 30 + 115 + 225 + passive_level * 3
    hit: 15
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 6
    v_increment: 2
    v_crit: true
  에테르(자연 회복):
    cooltime: 0
    delay: 10020
    damage: 0
    hit: 0
    remain: 9999999
    summondelay: 0
    type: SummonSkill
  레조넌스:
    cooltime: 10000
    delay: 690
    name: 레조넌스
    damage: "(120+125+265+passive_level*3) * (1.15**5)"
    hit: 6
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 4
    v_increment: 2
    v_crit: false
  레조넌스(스택):
    cooltime: -1
    delay: 0
    name: 레조넌스(스택)
    remain: 30000
    type: BuffSkill
    pdamage_indep: 10
    armor_ignore: 10
  테리토리:
    cooltime: 30000
    delay: 405
    name: 테리토리
    red: true
    rem: false
    damage: 100+300+passive_level*5
    hit: 4
    remain: 11000
    summondelay: 420
    type: SummonSkill
    enhanced_by_v: true
    upgrade_priority: 2
    v_increment: 2
    v_crit: false
  테리토리(종료):
    cooltime: -1
    delay: 0
    damage: 550+300+passive_level*5
    hit: 12
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 2
    v_increment: 2
    v_crit: false
  디바이드:
    cooltime: 0
    delay: 600
    damage: 375 + combat * 3
    hit: 6
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 0
    v_increment: 2
    v_crit: false
    modifier:
      pdamage: 20
  그레이브:
    cooltime: 90000
    delay: 630
    red: true
    rem: false
    damage: 820
    hit: 10
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 1
    v_increment: 2
    v_crit: false
  그레이브(디버프):
    cooltime: -1
    delay: 0
    remain: 999999999
    type: BuffSkill
    pdamage: 20
    armor_ignore: 10
  블로섬:
    cooltime: 15000
    delay: 420
    red: true
    rem: false
    damage: 650 + combat * 6
    hit: 8
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 3
    v_increment: 2
    v_crit: false
  마커:
    cooltime: 60000
    delay: 690
    damage: 500
    hit: 12
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 4
    v_increment: 2
    v_crit: false
    modifier:
      pdamage_indep: 300
  스콜:
    cooltime: 180000
    delay: 690
    damage: 1000
    hit: 12
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 3
    v_increment: 2
    v_crit: false
  레이스 오브 갓:
    cooltime: 120000
    delay: 0
    remain: 60000
    type: BuffSkill
    pdamage: 10
  루인(시전):
    cooltime: 60000
    delay: 600
    red: true
    damage: 0
    hit: 0
    type: DamageSkill
    tier: 5
    use_priority: 2
    upgrade_priority: 2
  루인(소환):
    cooltime: -1
    delay: 160
    damage: 250 + lv * 10
    hit: 6
    remain: 2000
    summondelay: 0
    type: SummonSkill
    tier: 5
    use_priority: 2
    upgrade_priority: 2
  루인(공격):
    cooltime: -1
    delay: 250
    red: false
    rem: false
    damage: 450 + lv * 18
    hit: 9
    remain: 2000
    summondelay: 0
    type: SummonSkill
    tier: 5
    use_priority: 2
    upgrade_priority: 2
  인피니트:
    cooltime: 180000
    delay: 342
    red: true
    damage: 350 + lv * 14
    hit: 12
    remain: 30000
    summondelay: 540
    type: SummonSkill
    tier: 5
    use_priority: 0
    upgrade_priority: 0
  리스토어:
    cooltime: 180000
    delay: 720
    red: true
    remain: 30000
    type: BuffSkill
    tier: 5
    use_priority: 1
    upgrade_priority: 1
    pdamage: 15 + lv
  리스토어(주기공격):
    cooltime: -1
    delay: 2970
    damage: 900 + 36 * lv
    hit: 3
    remain: 30000
    summondelay: 0
    type: SummonSkill
    tier: 5
    use_priority: 1
    upgrade_priority: 1
  스톰:
    cooltime: 90000
    delay: 330
    red: true
    rem: false
    damage: 550
    hit: 2
    remain: 14000
    summondelay: 780
    type: SummonSkill
    tier: 5
    use_priority: 0
    upgrade_priority: 0
