# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest argparse
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: Lint with flake8
      run: |
        # Detect files changed my current commit
        echo $GITHUB_SHA
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."        
          if [[ ${changed_file} =~ "*.py" ]]; then flake8 ${changed_file} --count --select=E9,F63,F7,F82 --show-source --statistics
        done
        # stop the build if there are Python syntax errors or undefined names
        flake8 ${{ steps.files.outputs.all }} --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ${{ steps.files.outputs.all }} --count --exit-zero --max-complexity=10 --max-line-length=256 --statistics
